"""add_natproxy_status

Revision ID: 6f6e687b201d
Revises: ae93f7357766
Create Date: 2019-06-14 11:25:51.608416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f6e687b201d'
down_revision = 'ae93f7357766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_vip', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('natproxy_disconnect', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'natproxy_disconnect')
    op.drop_column('user', 'is_vip')
    # ### end Alembic commands ###
