"""init

Revision ID: ae93f7357766
Revises: 
Create Date: 2019-06-13 12:15:05.745018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae93f7357766'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('addr', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_user_addr'), 'user', ['addr'], unique=False)
    op.create_index(op.f('ix_user_deleted_at'), 'user', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_deleted_at'), table_name='user')
    op.drop_index(op.f('ix_user_addr'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
