"""add_kindle

Revision ID: d73781edf416
Revises: 6f6e687b201d
Create Date: 2019-06-18 17:59:49.813587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd73781edf416'
down_revision = '6f6e687b201d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kindle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('sender', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kindle_deleted_at'), 'kindle', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_kindle_sender'), 'kindle', ['sender'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kindle_sender'), table_name='kindle')
    op.drop_index(op.f('ix_kindle_deleted_at'), table_name='kindle')
    op.drop_table('kindle')
    # ### end Alembic commands ###
